### ISSUE TITLE
Error parsing multiple args in declarative hooks 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle#111]
When running from CLI:
```shell
tackle arg1 arg2 --pf yaml 
```
On the file `tackle.yaml` 
```yaml
foo<-: 
  bar: baz 
  args: ['bar']
```
We only get:

```yaml 
bar: arg2 
```

Should be:

```yaml 
bar: arg1 arg2 
```
