### ISSUE TITLE
Add `return` hook with interrupt 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle#112]
Right now there is no way to gracefully stop parsing without exiting completely. For instance:

```yaml
<-: 
  exec: 
    foo: bar 
    # Run some hook to return 
    exit->: return --if foo=='bar'    # Not possible 
    some: other context 
```

It is not simple to do this as the parser will continue to parse unless it has been given some kind of interrupt to tell it to stop parsing.

Couple options:
1. Add a bool INTERRUPT variable in parser and check that when in walk_sync to stop parsing
2. Add bool field in Context from hook and check that
- Would additionally need to load that into the context when parsing hook 

Option 1 seems like the most reasonable
