### ISSUE TITLE
Expose configuring declarative hook `config` to allow `extra.ignore`

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle#115]
Per title, would be great to expose this to user for declarative hooks. 

```yaml 
foo<-: 
  bar: baz 
  config: 
    extra: ignore 
```
