### ISSUE TITLE
Allow declarative hook return to use value from private context 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle#116]
Per title, can only use vars from public context. 

Works

```yaml
<-: 
  return: foo 
  exec: 
     foo->: literal bar 
```

Broken 

```yaml
<-: 
  return: foo 
  exec: 
     foo_>: literal bar 
```
