### ISSUE TITLE
Allow using `--merge` in declarative hook field and fix error 

### ISSUE THREAD

**Issue by robcxyz** [robcxyz/tackle#117]
Can't use `--merge` in hook field right now but no reason why you should not be able to right?

At least fix the erroneous error. 

Broken: 

```yaml
manifest<-:
  target: str
  args: ['target']
  globals->: get_context --merge
  exec:
    render_target->: target_to_tmp {{target}}
```
```text
tackle.exceptions.FunctionCallException: Error parsing input_file='.tackle.yaml' at key_path='' 
Error parsing declarative hook field='globals'. Must produce an output for the field's default.
```

Working: 

```yaml
manifest<-:
  target: str
  args: ['target']
  exec:
    render_target->: target_to_tmp {{target}}
    globals->: get_context --merge  
```
